set_property SRC_FILE_INFO {cfile:/home/lnc3770a/Cours/MASTER/Simul_archi_mat/zybo-tp1/zybo-tp1.srcs/constrs_1/new/pulse_gen.xdc rfile:../../../zybo-tp1.srcs/constrs_1/new/pulse_gen.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports MCLK]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports P]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports RST]
